# Generated by Django 6.0.1 on 2026-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Croissants', 'Круассаны'), ('Breads', 'Хлеб'), ('Pastries', 'Выпечка'), ('Cakes', 'Торты'), ('Cookies', 'Печенье'), ('Buns', 'Булочки')], default='Pastries', max_length=50),
        ),
    ]
